// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/kgs.proto

package kgspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_proto_kgs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kgs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_kgs_proto_rawDescGZIP(), []int{0}
}

type GetKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyResponse) Reset() {
	*x = GetKeyResponse{}
	mi := &file_proto_kgs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyResponse) ProtoMessage() {}

func (x *GetKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kgs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_kgs_proto_rawDescGZIP(), []int{1}
}

func (x *GetKeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReturnKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnKeyRequest) Reset() {
	*x = ReturnKeyRequest{}
	mi := &file_proto_kgs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnKeyRequest) ProtoMessage() {}

func (x *ReturnKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kgs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnKeyRequest.ProtoReflect.Descriptor instead.
func (*ReturnKeyRequest) Descriptor() ([]byte, []int) {
	return file_proto_kgs_proto_rawDescGZIP(), []int{2}
}

func (x *ReturnKeyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type ReturnKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReturnKeyResponse) Reset() {
	*x = ReturnKeyResponse{}
	mi := &file_proto_kgs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReturnKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReturnKeyResponse) ProtoMessage() {}

func (x *ReturnKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_kgs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReturnKeyResponse.ProtoReflect.Descriptor instead.
func (*ReturnKeyResponse) Descriptor() ([]byte, []int) {
	return file_proto_kgs_proto_rawDescGZIP(), []int{3}
}

func (x *ReturnKeyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_kgs_proto protoreflect.FileDescriptor

const file_proto_kgs_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/kgs.proto\x12\x03kgs\"\x0f\n" +
	"\rGetKeyRequest\"\"\n" +
	"\x0eGetKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"$\n" +
	"\x10ReturnKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"-\n" +
	"\x11ReturnKeyResponse\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess2\x85\x01\n" +
	"\x14KeyGenerationService\x121\n" +
	"\x06GetKey\x12\x12.kgs.GetKeyRequest\x1a\x13.kgs.GetKeyResponse\x12:\n" +
	"\tReturnKey\x12\x15.kgs.ReturnKeyRequest\x1a\x16.kgs.ReturnKeyResponseB2Z0github.com/Nikhil-O1O5/url-shortener/proto/kgspbb\x06proto3"

var (
	file_proto_kgs_proto_rawDescOnce sync.Once
	file_proto_kgs_proto_rawDescData []byte
)

func file_proto_kgs_proto_rawDescGZIP() []byte {
	file_proto_kgs_proto_rawDescOnce.Do(func() {
		file_proto_kgs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_kgs_proto_rawDesc), len(file_proto_kgs_proto_rawDesc)))
	})
	return file_proto_kgs_proto_rawDescData
}

var file_proto_kgs_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_kgs_proto_goTypes = []any{
	(*GetKeyRequest)(nil),     // 0: kgs.GetKeyRequest
	(*GetKeyResponse)(nil),    // 1: kgs.GetKeyResponse
	(*ReturnKeyRequest)(nil),  // 2: kgs.ReturnKeyRequest
	(*ReturnKeyResponse)(nil), // 3: kgs.ReturnKeyResponse
}
var file_proto_kgs_proto_depIdxs = []int32{
	0, // 0: kgs.KeyGenerationService.GetKey:input_type -> kgs.GetKeyRequest
	2, // 1: kgs.KeyGenerationService.ReturnKey:input_type -> kgs.ReturnKeyRequest
	1, // 2: kgs.KeyGenerationService.GetKey:output_type -> kgs.GetKeyResponse
	3, // 3: kgs.KeyGenerationService.ReturnKey:output_type -> kgs.ReturnKeyResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_kgs_proto_init() }
func file_proto_kgs_proto_init() {
	if File_proto_kgs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_kgs_proto_rawDesc), len(file_proto_kgs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_kgs_proto_goTypes,
		DependencyIndexes: file_proto_kgs_proto_depIdxs,
		MessageInfos:      file_proto_kgs_proto_msgTypes,
	}.Build()
	File_proto_kgs_proto = out.File
	file_proto_kgs_proto_goTypes = nil
	file_proto_kgs_proto_depIdxs = nil
}
