// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/kgs.proto

package kgspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyGenerationService_GetKey_FullMethodName    = "/kgs.KeyGenerationService/GetKey"
	KeyGenerationService_ReturnKey_FullMethodName = "/kgs.KeyGenerationService/ReturnKey"
)

// KeyGenerationServiceClient is the client API for KeyGenerationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyGenerationServiceClient interface {
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	ReturnKey(ctx context.Context, in *ReturnKeyRequest, opts ...grpc.CallOption) (*ReturnKeyResponse, error)
}

type keyGenerationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyGenerationServiceClient(cc grpc.ClientConnInterface) KeyGenerationServiceClient {
	return &keyGenerationServiceClient{cc}
}

func (c *keyGenerationServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KeyGenerationService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyGenerationServiceClient) ReturnKey(ctx context.Context, in *ReturnKeyRequest, opts ...grpc.CallOption) (*ReturnKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReturnKeyResponse)
	err := c.cc.Invoke(ctx, KeyGenerationService_ReturnKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyGenerationServiceServer is the server API for KeyGenerationService service.
// All implementations must embed UnimplementedKeyGenerationServiceServer
// for forward compatibility.
type KeyGenerationServiceServer interface {
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	ReturnKey(context.Context, *ReturnKeyRequest) (*ReturnKeyResponse, error)
	mustEmbedUnimplementedKeyGenerationServiceServer()
}

// UnimplementedKeyGenerationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyGenerationServiceServer struct{}

func (UnimplementedKeyGenerationServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeyGenerationServiceServer) ReturnKey(context.Context, *ReturnKeyRequest) (*ReturnKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReturnKey not implemented")
}
func (UnimplementedKeyGenerationServiceServer) mustEmbedUnimplementedKeyGenerationServiceServer() {}
func (UnimplementedKeyGenerationServiceServer) testEmbeddedByValue()                              {}

// UnsafeKeyGenerationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyGenerationServiceServer will
// result in compilation errors.
type UnsafeKeyGenerationServiceServer interface {
	mustEmbedUnimplementedKeyGenerationServiceServer()
}

func RegisterKeyGenerationServiceServer(s grpc.ServiceRegistrar, srv KeyGenerationServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyGenerationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyGenerationService_ServiceDesc, srv)
}

func _KeyGenerationService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenerationServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyGenerationService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenerationServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyGenerationService_ReturnKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReturnKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyGenerationServiceServer).ReturnKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyGenerationService_ReturnKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyGenerationServiceServer).ReturnKey(ctx, req.(*ReturnKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyGenerationService_ServiceDesc is the grpc.ServiceDesc for KeyGenerationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyGenerationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kgs.KeyGenerationService",
	HandlerType: (*KeyGenerationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKey",
			Handler:    _KeyGenerationService_GetKey_Handler,
		},
		{
			MethodName: "ReturnKey",
			Handler:    _KeyGenerationService_ReturnKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/kgs.proto",
}
